SDK-7571: Added script to launch inference and retrieve logs
neurala/aitrios-tools pull request #2
Opened 2024-09-30 18:44 UTC by jraynal

Changelog
=======

- Added script to launch processing on a camera and retrieve logs

2024-10-04 21:17 UTC, jgerityneurala requested changes
I had a bunch of little comments but overall this looks functional and maintainable.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/README.md
> +```
I've found that I usually would rather just point the reader to running the tool with `--help`, it's a nuisance to keep this kind of thing up to date. The example invocation is handy, though.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    jsonschema.validate(configuration, json_schema)
With `Path` there's an alternate spelling here that is slightly more compact. No strong perference to one over another, though. I would probably leave off the comments

```suggestion
    configuration = json.loads(configuration_path.read_text())
    json_schema = json.loads(schema_path.read_text())

    jsonschema.validate(configuration, json_schema)
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +def load_configuration_file(configuration_path: Path, schema_path: Path):
Could also annotate the return type here, although it's not possible to be too specific. Helps to hint at the type at least.

```suggestion
def load_configuration_file(configuration_path: Path, schema_path: Path) -> dict:
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    json_load = load_configuration_file(
I would probably call the result of the load `config` here, `json_load` tripped me up on first reading.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    print("Starting processing")
In cases like this I would just omit the comments, since they're duplicating what's being printed. If it's mostly being used to separate the distinct steps, I usually consider that a good sign to write separate functions for each step.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    Dumnp data as a JSON element, pretty formated
Typo

```suggestion
    Dump data as a JSON element, pretty formated
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    Parse a secrects configuration file, validates against schema
Typo, wording

```suggestion
    Parse a secrets configuration file, validate against schema
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    help=f"The path to your AITIRIOS console configuration file",
Typo, unnecessary f-string

```suggestion
    help="The path to your AITRIOS console configuration file",
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    help=f"Device Name to search for",
Unnecessary f-string

```suggestion
    help="Device Name to search for",
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +def jsonify(data):
I'd personally rather just see `json.dumps()` at the site of use for the sake of legibility, but I don't object to this wrapper.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    if not devices or len(devices) == 0:
Why not just `if not devices:`? Empty containers are usually false-y but I don't know if `GetDevices()` frustrates that expectation

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    )
I'd say this should either be one line, or each arg should get its own line.

```suggestion
    request = client_obj.GetDevices(
        connectionState="connected",
        device_name=args.device_name
    )
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    # Hardcoding "top" here to return the N latest logs
Would be polite to the user to represent that top-N behavior in the printed output

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    # while not result:
Dead code

```suggestion
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/requirements.txt
> +git+https://github.com/SonySemiconductorSolutions/aitrios-sample-application-keypoint-detection@v1.0.1#egg=console-access-api&subdirectory=backend/lib/console-access-api
It's not required but I like to specify the project name when using a VCS requirement

```suggestion
console-access-api @ git+https://github.com/SonySemiconductorSolutions/aitrios-sample-application-keypoint-detection@v1.0.1#egg=console-access-api&subdirectory=backend/lib/console-access-api
```

Very fancy, nicely done. Any reason to prefer `git+https` over `git+ssh` here? I find that the former is more convenient on Windows (getting SSH auth to work is mildly annoying there) and the latter is more convenient on Linux. No strong preference, but I usually write `git+ssh` and deal with it on Windows when I have to.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    dest="aitrios_secrets",
If a long name is given, it's always used for `dest`, this can be omitted

```suggestion
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    dest="device_name",
If a long name is given, it's always used for `dest`, this can be omitted

```suggestion
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +        print(f"Connected Devices")
Unnecessary f-string

```suggestion
        print("Connected Devices")
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    if not "SUCCES" in response["result"]:
Is that a typo on our end, or Sony's?

```suggestion
    if not "SUCCESS" in response["result"]:
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    time.sleep(10)
Might be worth putting a print here to say that we're waiting on the camera?

Also, typo

```suggestion
    # Wait for processing to do something useful
    time.sleep(10)
```

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +    client_obj = create_client(args.aitrios_secrets)
I'd probably just call it `client` but it's legible as-is.

2024-10-04 21:17 UTC, jgerityneurala commented on execute/execute.py
> +if __name__ == "__main__":
This block is long enough that I'd probably at least define `def main(args): ...` and only call `args = parser.parse_args(); main(args)` in the block itself, but see my other comment about possibly splitting up the steps.

2024-10-08 19:45 UTC, jraynal commented on execute/execute.py
> +    jsonschema.validate(configuration, json_schema)
`loads` didn't work for some reason.

2024-10-08 19:46 UTC, jraynal commented on execute/README.md
> +```
I know we disagree on putting the help. I find it comforting when I need a quick reference, even if there is a chance it's obsolete, at least at some point it was right.

2024-10-08 19:49 UTC, jraynal commented on execute/execute.py
> +    if not "SUCCES" in response["result"]:
Mine. Substring works no? :D

2024-10-08 19:54 UTC, jraynal commented on execute/execute.py
> +def jsonify(data):
If I didn't have the indentation set to non-default I would.

2024-10-08 19:54 UTC, jgerityneurala commented on execute/execute.py
> +    if not "SUCCES" in response["result"]:
It 'works' by coincidence, yea

2024-10-08 19:55 UTC, jgerityneurala commented on execute/README.md
> +```
:shrug:

2024-10-08 19:55 UTC, jraynal commented on execute/execute.py
> +    if not devices or len(devices) == 0:
No, I think I was having issues... until I realized I was piping the script into `jq` :D

2024-10-08 19:55 UTC, jraynal commented on execute/execute.py
> +    )
Use `black` to format.

2024-10-08 21:13 UTC, jraynal commented on execute/execute.py
> +if __name__ == "__main__":
Done

2024-10-08 21:14 UTC, jraynal commented on execute/execute.py
> +    print("Starting processing")
Done, although there is more logs now.. I don't know yet if it's a problem or not. Not too concerned at this stage.

2024-10-25 20:14 UTC, merged